name: Build Node PAC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 4320
    steps:
    - uses: actions/checkout@v2
    - name: Prepare to build Node
      run: ./start-build-node-docker-arm64-amazon.sh
    - name: Build Node first attempt
      run: ./continue-container-build.sh
      timeout-minutes: 4320
    - name: Build Node second attempt
      run: ./continue-container-build.sh
      timeout-minutes: 4320
    - name: Build Node third attempt
      run: ./continue-container-build.sh
      timeout-minutes: 4320
    - name: Build Node fourth attempt
      run: ./continue-container-build.sh
      timeout-minutes: 4320
            